version: 0.1
env:
  secrets-manager:
    TOKEN: sonarcloud:TOKEN
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=aws-security-dev-testing-thing_aws-security-dev-testing-thing -Dsonar.organization=aws-security-dev-testing-thing -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$TOKEN 